title: Unredacted
description: Thoughts and opinions of a software designer.
tagline: Email the author.
keywords:
  - Reda
  - Lemeden
  - kaishinlab
  - unredacted
  - design
  - kaishin
baseurl: ""
google_verification: "ycRyf86T2D5nz7uhxafC3bEXqGAxgea8SXR44B78Lvk"
gems:
  - jekyll-sitemap

url: http://unredacted.redalemeden.com
future: false
show_drafts: false
limit_posts: 0
paginate: 5
paginate_path: "/page-:num"
reading_time: true
wpm: 200

author:
  name: Reda Lemeden

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:title/
exclude: [
  "node_modules",
  "gulp.js",
  "gulpfile.coffee",
  "package.json",
  "README.md",
  "Gemfile",
  "Gemfile.lock"
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
